name: walsh
favicon: null
layout_spectrum: 0.56806
typography_spectrum: 0.15497
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Walsh Cairnes & Co'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff0000'
    - '#010101'
    - '#ffadad'
    - '#ff5b5b'
  brandStrength: 0.125
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
