name: walsh
favicon: null
layout_spectrum: 0.2837515
typography_spectrum: 0.15497
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#90b6cd'
    - '#705c18'
    - '#f5cfa2'
    - '#c99945'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
