name: walsh
favicon: null
layout_spectrum: 0.28224642877466977
typography_spectrum: 0.9893390021752566
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7715842700563371
  lightness: 0.7861627477686852
  saturation: 0.4619978158734739
  rhythmicContrast: 0.9024085691198707
purpose: []
