name: walsh
favicon: null
layout_spectrum: 0.2837515
typography_spectrum: 0.15497
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fe0000'
    - '#010101'
    - '#ff9293'
    - '#6b6b6b'
  brandStrength: 0.1875
  lightness: 0.7861627477686852
  saturation: 0.4619978158734739
  rhythmicContrast: 0.9024085691198707
purpose: []
