name: walsh
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15497
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1c2a7'
    - '#836108'
    - '#1a150c'
    - '#ffffff'
    - '#958d88'
  brandStrength: 0.7715842700563371
  lightness: 0.7861627477686852
  saturation: 0.4619978158734739
  rhythmicContrast: 0.9024085691198707
purpose: []
