name: walsh
favicon: null
layout_spectrum: 0.50534
typography_spectrum: 0.49679
title: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040104'
    - '#8A8688'
    - '#FBFAFB'
    - '#B40203'
    - '#FB5441'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
