title: 'Walsh Cairnes & Co'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7855436
  brandStrength: 0.8870967
  lightness: 0.3769414
  brandColors:
    - '#040104'
    - '#8A8688'
    - '#FBFAFB'
    - '#B40203'
    - '#FB5441'
  rhythmicContrast: 0.6051373
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: walsh
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.15497
layout_spectrum: 0
